/* =============================================
   LANG: 🇻🇳 Tiếng Việt (VI)
   Chủ đề G – Hướng nghiệp với Tin học
============================================= */
window.LANGS = window.LANGS || {};
window.LANGS['vi'] = {
// ── Header / Nav ──────────────────────────────────────────
    badge:'Chủ đề G - Hướng nghiệp với Tin học',
    h1line1:'Khám Phá Ngành<br>Công Nghệ Thông Tin',
    subtitle:'Giới thiệu nhóm nghề Dịch vụ, Quản trị và Ứng dụng CNTT',
    readtime:'Thời gian đọc:',
    nav1:'Bài giới thiệu', nav2:'Các bài viết', nav3:'Góc ảnh',
    nav4:'Góc âm nhạc, video', nav5:'Khám phá nghề', nav6:'Bình chọn', nav7:'Góc bình luận',
    // ── Section titles ────────────────────────────────────────
    sec1:'Bài giới thiệu', sec2:'Các bài viết', sec3:'Góc ảnh',
    sec4:'Góc âm nhạc, video clip', sec7:'Góc bình luận',
    copylink:'Copy link',
    themeLight:'Sáng', themeDark:'Tối',
    readingMin:'phút',
    // ── Intro section ─────────────────────────────────────────
    intro_title:'Chủ đề G – Hướng nghiệp với Tin học',
    intro_p1:'Công nghệ thông tin (CNTT) là ngành đang phát triển mạnh mẽ và có nhu cầu nhân lực rất cao tại Việt Nam. Việt Nam đang thực hiện <strong style="color:#ff9999;">Chương trình Chuyển đổi số quốc gia</strong> được Thủ tướng Chính phủ phê duyệt tháng 6 năm 2020, tạo ra hàng chục nghìn cơ hội việc làm mỗi năm.',
    intro_p2:'<strong style="color:#ff9999;">Bài 1</strong> giới thiệu nhóm nghề <em>Dịch vụ</em> (Kĩ thuật viên CNTT, Kĩ sư An toàn Thông tin) và nhóm nghề <em>Quản trị</em> (Kĩ sư Quản trị Mạng, Quản trị và Bảo trì Hệ thống).',
    intro_p3:'<strong style="color:#ff9999;">Bài 2</strong> giới thiệu các nghề trong ngành <em>Công nghiệp phần mềm</em> (3 nghề), <em>Chuyển đổi số</em> (3 nghề), <em>Truyền thông đa phương tiện</em> (4 nghề) và <em>Ứng dụng CNTT các ngành khác</em> (3 nghề).',
    stat1:'Kĩ sư IT tuyển dụng mỗi năm tại Việt Nam',
    stat2:'Nhóm nghề trong Bài 1 (Dịch vụ & Quản trị)',
    stat3:'Nhóm nghề trong Bài 2',
    stat4:'Tổng số nghề được giới thiệu trong Chủ đề G',
    // ── Flip card group headings ──────────────────────────────
    nhom_dv:'BÀI 1 – NHÓM NGHỀ DỊCH VỤ TRONG NGÀNH CNTT',
    nhom_qt:'BÀI 1 – NHÓM NGHỀ QUẢN TRỊ TRONG NGÀNH CNTT',
    nhom_pm:'BÀI 2 – NHÓM 1: MỘT SỐ NGHỀ TRONG NGÀNH CÔNG NGHIỆP PHẦN MỀM',
    nhom_cds:'BÀI 2 – NHÓM 2: CHUYỂN ĐỔI SỐ VÀ MỘT SỐ NGHỀ LIÊN QUAN',
    nhom_tt:'BÀI 2 – NHÓM 3: MỘT SỐ NGHỀ ỨNG DỤNG CNTT TRONG NGÀNH TRUYỀN THÔNG ĐA PHƯƠNG TIỆN',
    nhom_ud:'BÀI 2 – NHÓM 4: MỘT SỐ NGHỀ ỨNG DỤNG CNTT TRONG CÁC NGÀNH KHÁC',
    // ── Photo captions ────────────────────────────────────────
    cap1:'Kĩ thuật viên CNTT sửa chữa và bảo trì phần cứng máy tính',
    cap2:'Trung tâm điều hành an toàn thông tin (SOC) giám sát 24/7',
    cap3:'Kĩ sư quản trị mạng vận hành hệ thống mạng doanh nghiệp',
    cap4:'Kĩ sư AI nghiên cứu và phát triển mô hình trí tuệ nhân tạo',
    cap5:'GIS xây dựng bản đồ số ứng dụng quy hoạch đô thị',
    cap6:'Nhà thiết kế UI/UX xây dựng giao diện và trải nghiệm người dùng',
    // ── Video cards ───────────────────────────────────────────
    vid1_title:'Kĩ thuật viên CNTT – Công việc hằng ngày',
    vid1_desc:'Tìm hiểu thực tế công việc của kĩ thuật viên IT tại Việt Nam',
    vid2_title:'Kĩ sư An toàn Thông tin – Nghề hot thời đại số',
    vid2_desc:'Vì sao an toàn thông tin là lĩnh vực được săn đón nhất hiện nay?',
    vid3_title:'Chuyển đổi số – Cơ hội nghề nghiệp mới',
    vid3_desc:'Kĩ sư AI, IoT, Đám mây – những nghề của tương lai số',
    vid4_title:'Hướng nghiệp – Chọn ngành CNTT phù hợp bản thân',
    vid4_desc:'Gợi ý cách chọn nghề phù hợp với sở thích và năng lực của bạn',
    // ── Flip card content ─────────────────────────────────────
    flip_hint:'🔄 Hover để xem thêm',
    // Kĩ thuật viên CNTT
    ktvcntt_tooltip:'Người hỗ trợ kỹ thuật phần cứng + phần mềm tại tổ chức',
    ktvcntt_title:'a) Kĩ thuật viên Công nghệ Thông tin',
    ktvcntt_desc:'Kĩ thuật viên công nghệ thông tin là người làm những công việc cần đến kiến thức và kĩ năng về CNTT (phần cứng và phần mềm) tại các tổ chức, doanh nghiệp.',
    ktvcntt_li1:'Khắc phục lỗi, sửa chữa máy tính cho khách hàng',
    ktvcntt_li2:'Tư vấn nâng cấp phần cứng, phần mềm',
    ktvcntt_li3:'Lắp đặt thiết bị, thiết lập kết nối mạng',
    ktvcntt_li4:'Quản lí máy tính, thiết bị ngoại vi',
    ktvcntt_back_h:'💡 Lương & Yêu cầu',
    ktvcntt_back1:'Lương khởi điểm: 8–15 triệu/tháng',
    ktvcntt_back2:'Có kinh nghiệm: 15–30 triệu/tháng',
    ktvcntt_back3:'Cần: Kiến thức phần cứng, Windows/Linux',
    ktvcntt_back4:'Bằng cấp: CĐ/ĐH CNTT hoặc chứng chỉ CompTIA A+',
    ktvcntt_back5:'Tính cách phù hợp: Kiên nhẫn, tỉ mỉ, thích giải quyết vấn đề',
    // Kĩ sư An toàn Thông tin
    attt_tooltip:'Bảo vệ hệ thống khỏi tấn công mạng & rò rỉ dữ liệu',
    attt_title:'b) Kĩ sư An toàn Thông tin',
    attt_desc:'Xây dựng và duy trì các giải pháp an toàn dữ liệu, bảo mật thông tin và khôi phục hệ thống khi sự cố xảy ra.',
    attt_li1:'Thiết lập và hướng dẫn quy định an toàn thông tin',
    attt_li2:'Theo dõi, báo động khi có tín hiệu đáng ngờ',
    attt_li3:'Lập và triển khai kế hoạch xử lí sự cố',
    attt_li4:'Tư vấn an toàn thông tin cho bộ phận phát triển',
    attt_back_h:'💡 Lương & Yêu cầu',
    attt_back1:'Lương khởi điểm: 15–25 triệu/tháng',
    attt_back2:'Senior: 40–80 triệu/tháng',
    attt_back3:'Chứng chỉ: CEH, CISSP, CompTIA Security+',
    attt_back4:'Kỹ năng: Penetration testing, mã hóa, firewall',
    attt_back5:'Tính cách phù hợp: Tư duy phân tích, cẩn trọng',
    // Kĩ sư Quản trị Mạng
    qtm_tooltip:'Đảm bảo hệ thống mạng luôn thông suốt & an toàn',
    qtm_title:'a) Kĩ sư Quản trị Mạng',
    qtm_desc:'Đảm bảo hệ thống mạng máy tính luôn thông suốt và hoạt động an toàn. Bao gồm quản lí, vận hành, cấu hình và bảo vệ mạng.',
    qtm_li1:'Quản lí thiết bị mạng, cấu hình và điều chỉnh hiệu năng',
    qtm_li2:'Bảo vệ mạng trước tấn công, truy cập bất hợp pháp',
    qtm_li3:'Khắc phục sự cố mạng',
    qtm_back_h:'💡 Lương & Yêu cầu',
    qtm_back1:'Lương: 12–30 triệu/tháng',
    qtm_back2:'Chứng chỉ: CCNA, CCNP (Cisco)',
    qtm_back3:'Kỹ năng: TCP/IP, VPN, Routing & Switching',
    qtm_back4:'Tính cách: Kỹ lưỡng, xử lý nhanh sự cố',
    // Quản trị và Bảo trì Hệ thống
    btht_tooltip:'Quản lý toàn bộ hệ thống CNTT của tổ chức',
    btht_title:'b) Quản trị và Bảo trì Hệ thống',
    btht_desc:'Quản lí cả phần mềm và phần cứng liên quan đến vận hành hệ thống mạng máy tính và truyền thông dữ liệu.',
    btht_li1:'Phân tích nhu cầu về hệ thống thông tin của tổ chức',
    btht_li2:'Cài đặt phần cứng và phần mềm cho hệ thống mạng',
    btht_li3:'Tối ưu hoá và đánh giá hoạt động hệ thống',
    btht_back_h:'💡 Lương & Yêu cầu',
    btht_back1:'Lương: 15–35 triệu/tháng',
    btht_back2:'Kỹ năng: Windows Server, Linux, VMware',
    btht_back3:'Cần biết: Active Directory, backup, monitoring',
    btht_back4:'Tính cách: Có trách nhiệm, tư duy hệ thống',
    // Kiểm thử viên
    ktv_title:'a) Kiểm thử viên',
    ktv_desc:'Chạy thử phần mềm để xác nhận đáp ứng đúng các yêu cầu thiết kế và vận hành, tìm và báo cáo lỗi cho nhóm phát triển.',
    ktv_note:'<strong style="color:#ff9999;"><img src="images/check (1).png" alt="" style="width:20px;height:20px;vertical-align:text-bottom;"> Không nhất thiết phải biết lập trình cao!</strong>',
    ktv_back_h:'💡 Lương & Yêu cầu',
    ktv_back1:'Lương: 8–20 triệu/tháng',
    ktv_back2:'Chứng chỉ: ISTQB Foundation Level',
    ktv_back3:'Kỹ năng: Test case, bug report, Jira, Selenium',
    ktv_back4:'Không cần lập trình giỏi — cần tư duy logic',
    ktv_back5:'Tính cách: Tỉ mỉ, kiên nhẫn, hay đặt câu hỏi',
    // Người quản lí Kiểm thử
    qlkt_title:'b) Người quản lí Kiểm thử',
    qlkt_desc:'Lập quy trình kiểm thử, viết kịch bản chạy thử, lập kế hoạch và phân công công việc cho các kiểm thử viên thực hiện.',
    qlkt_back_h:'💡 Lương & Yêu cầu',
    qlkt_back1:'Lương: 20–45 triệu/tháng',
    qlkt_back2:'Kinh nghiệm: 3–5 năm làm kiểm thử viên',
    qlkt_back3:'Kỹ năng: Quản lý dự án, lập kế hoạch kiểm thử',
    qlkt_back4:'Tính cách: Lãnh đạo, giao tiếp tốt, quyết đoán',
    // Nhà thiết kế UI/UX
    uiux_title:'c) Nhà thiết kế giao diện người dùng &amp; Nhà thiết kế trải nghiệm người dùng (UI/UX)',
    uiux_desc:'Đảm bảo sản phẩm phần mềm thân thiện, hấp dẫn và dễ sử dụng. Sử dụng kiến thức tâm lí học, y sinh học để điều chỉnh tính năng phù hợp với người dùng.',
    uiux_note:'<strong style="color:#ff9999;">Không cần kĩ năng lập trình — cần tư duy sáng tạo!</strong>',
    uiux_back_h:'💡 Lương & Công cụ',
    uiux_back1:'Lương: 12–35 triệu/tháng; Senior: 50 triệu+',
    uiux_back2:'Công cụ: Figma, Adobe XD, Sketch, Zeplin',
    uiux_back3:'Portfolio thiết kế là yêu cầu quan trọng',
    uiux_back4:'Hiểu biết về tâm lý học màu sắc, UX research',
    uiux_back5:'Tính cách: Sáng tạo, đồng cảm với người dùng',
    // Kĩ sư Điện toán Đám mây
    cloud_title:'a) Kĩ sư Điện toán Đám mây',
    cloud_desc:'Thiết kế, phát triển, bảo trì và khắc phục sự cố cơ sở hạ tầng đám mây. Sử dụng máy chủ Internet để lưu trữ, xử lí và phân tích dữ liệu.',
    cloud_back_h:'💡 Lương & Yêu cầu',
    cloud_back1:'Lương: 20–50 triệu/tháng',
    cloud_back2:'Chứng chỉ: AWS Solutions Architect, GCP, Azure',
    cloud_back3:'Kỹ năng: Docker, Kubernetes, Terraform, CI/CD',
    cloud_back4:'Tính cách: Tư duy hạ tầng, thích tự động hóa',
    // Kĩ sư IoT
    iot_title:'b) Kĩ sư IoT',
    iot_desc:'Thiết kế, phát triển, triển khai và bảo trì các hệ thống IoT — mạng lưới thiết bị trao đổi thông tin theo thời gian thực.',
    iot_back_h:'💡 Lương & Yêu cầu',
    iot_back1:'Lương: 15–40 triệu/tháng',
    iot_back2:'Kỹ năng: Embedded C, MQTT, Raspberry Pi, Arduino',
    iot_back3:'Kết hợp: Điện tử + Phần mềm + Mạng',
    iot_back4:'Tính cách: Thích phần cứng lẫn phần mềm',
    // Kĩ sư Trí tuệ Nhân tạo (AI)
    ai_title:'Kĩ sư Trí tuệ Nhân tạo (AI)',
    ai_desc:'Xây dựng mô hình AI, quản lí quy trình phát triển AI và đảm bảo các kết quả nghiên cứu AI mới nhất được triển khai vào sản xuất. Lĩnh vực nóng nhất hiện nay.',
    ai_back_h:'💡 Lương & Yêu cầu',
    ai_back1:'Lương: 25–80 triệu/tháng; Senior: 100 triệu+',
    ai_back2:'Kỹ năng: Python, TensorFlow, PyTorch, ML pipelines',
    ai_back3:'Toán học: Đại số tuyến tính, xác suất thống kê',
    ai_back4:'Tính cách: Ham nghiên cứu, tư duy phân tích cao',
    // Chuyên viên Thiết kế Đồ hoạ
    thietkedohoa_title:'a) Chuyên viên Thiết kế Đồ hoạ',
    thietkedohoa_desc:'Chọn kiểu chữ, màu sắc, hình khối, hình ảnh và bài trí tổng thể sản phẩm đồ hoạ bằng Photoshop, Illustrator, Sketch... Không cần lập trình.',
    thietkedohoa_back_h:'💡 Lương & Yêu cầu',
    thietkedohoa_back1:'Lương: 8–22 triệu/tháng; Freelance không giới hạn',
    thietkedohoa_back2:'Công cụ: Photoshop, Illustrator, CorelDRAW',
    thietkedohoa_back3:'Portfolio là yếu tố quyết định khi xin việc',
    thietkedohoa_back4:'Tính cách: Sáng tạo, có khiếu thẩm mỹ',
    // Chuyên viên Thiết kế Truyền thông Đa phương tiện
    ttdpt_title:'b) Chuyên viên Thiết kế Truyền thông Đa phương tiện',
    ttdpt_desc:'Thiết kế, xử lí và biên tập âm thanh, hình ảnh cho sản phẩm số, kết hợp kỹ thuật đa phương tiện và truyền thông đại chúng.',
    ttdpt_back_h:'💡 Lương & Yêu cầu',
    ttdpt_back1:'Lương: 10–25 triệu/tháng',
    ttdpt_back2:'Công cụ: Premiere Pro, After Effects, Audition',
    ttdpt_back3:'Cần: Kỹ năng kể chuyện bằng hình ảnh/âm thanh',
    ttdpt_back4:'Tính cách: Sáng tạo, nhạy cảm với nghệ thuật',
    // Nhà phát triển Trang web
    webdev_title:'c) Nhà phát triển Trang web',
    webdev_desc:'Thiết kế giao diện, lập trình trang web, kiểm tra và khắc phục sự cố về hiệu suất hoặc trải nghiệm người dùng.',
    webdev_back_h:'💡 Lương & Yêu cầu',
    webdev_back1:'Lương: 12–40 triệu/tháng; Fullstack: 50 triệu+',
    webdev_back2:'Frontend: HTML, CSS, JS, React/Vue',
    webdev_back3:'Backend: Node.js, PHP, Python, Java',
    webdev_back4:'Tính cách: Logic + sáng tạo, thích xây dựng',
    // Chuyên viên Kĩ xảo Điện ảnh
    vfx_title:'d) Chuyên viên Kĩ xảo Điện ảnh',
    vfx_desc:'Đảm bảo các hiệu ứng âm thanh, hình ảnh mang lại cảm xúc thật nhất và truyền tải đúng thông điệp của nhà sản xuất.',
    vfx_back_h:'💡 Lương & Yêu cầu',
    vfx_back1:'Lương: 15–50 triệu/tháng (theo dự án)',
    vfx_back2:'Công cụ: Nuke, Houdini, Maya, Blender',
    vfx_back3:'Ngành đang bùng nổ với phim VN và quảng cáo',
    vfx_back4:'Tính cách: Sáng tạo, chú ý từng chi tiết',
    // Nhà phân tích / Khoa học Dữ liệu
    data_title:'a) Nhà phân tích Dữ liệu &amp; Nhà khoa học Dữ liệu',
    data_desc:'Phân tích tập dữ liệu để xác định xu hướng, phát hiện bất thường và tri thức tiềm ẩn, làm cơ sở cho lãnh đạo ra quyết định.',
    data_back_h:'💡 Lương & Yêu cầu',
    data_back1:'Lương: 18–50 triệu/tháng',
    data_back2:'Kỹ năng: Python/R, SQL, Tableau, Power BI',
    data_back3:'Cần: Toán thống kê, tư duy phân tích dữ liệu',
    data_back4:'Tính cách: Tò mò, thích tìm pattern trong data',
    // Kĩ sư GIS
    gis_title:'b) Kĩ sư GIS (Hệ thống Thông tin Địa lí)',
    gis_desc:'Xây dựng bản đồ số, duy trì cơ sở dữ liệu địa lí và phân tích dữ liệu bằng các công cụ GIS cho nhiều lĩnh vực ứng dụng.',
    gis_back_h:'💡 Lương & Yêu cầu',
    gis_back1:'Lương: 12–28 triệu/tháng',
    gis_back2:'Công cụ: ArcGIS, QGIS, Python, PostGIS',
    gis_back3:'Ứng dụng: Đô thị, quốc phòng, môi trường',
    gis_back4:'Tính cách: Tỉ mỉ, thích làm việc với bản đồ/không gian',
    // Kĩ sư Công nghệ Tài chính (Fintech)
    fintech_title:'c) Kĩ sư Công nghệ Tài chính (Fintech)',
    fintech_desc:'Áp dụng công nghệ tiên tiến để cải thiện dịch vụ tài chính. Ứng dụng điện toán đám mây, phần mềm phân tích dữ liệu, AI vào tài chính – ngân hàng.',
    fintech_back_h:'💡 Lương & Yêu cầu',
    fintech_back1:'Lương: 20–60 triệu/tháng',
    fintech_back2:'Kỹ năng: Blockchain, API tài chính, bảo mật thanh toán',
    fintech_back3:'Kết hợp: CNTT + Tài chính – Ngân hàng',
    fintech_back4:'Tính cách: Cẩn thận, hiểu quy định tài chính',
    // ── Quiz ─────────────────────────────────────────────────
    quiz_sec_title:'🧠 Khám phá nghề phù hợp với bạn',
    quiz_intro_h:'Nghề IT nào dành cho bạn?',
    quiz_intro_p:'Trả lời 10 câu hỏi ngắn về tính cách và sở thích. Kết quả sẽ cho bạn thấy <strong style="color:var(--purple-light)">2 nghề phù hợp nhất</strong> cùng tỉ lệ % — vì đôi khi con đường bạn chọn không phải cái số 1!',
    quiz_start_btn:'BẮT ĐẦU KHÁM PHÁ →',
    quiz_q_label:'CÂU',
    quiz_rank1:'★ PHÙ HỢP NHẤT',
    quiz_rank2:'✦ GỢI Ý 2',
    quiz_match_label:'Mức độ phù hợp',
    quiz_learn_btn:'📖 Tìm hiểu thêm →',
    quiz_res_title:'Kết quả của bạn',
    quiz_res_sub:'Dựa trên câu trả lời, đây là 2 nghề phù hợp nhất với bạn',
    quiz_note_html:'<strong>💡 Lưu ý quan trọng:</strong> Kết quả này chỉ mang tính tham khảo dựa trên xu hướng tính cách. Nếu bạn thích nghề xếp thứ 2 hơn — <strong>hãy theo đuổi nó!</strong> Đam mê và nỗ lực luôn quan trọng hơn bất kỳ bài test nào.',
    quiz_restart_btn:'🔄 Làm lại',
    // ── Poll ─────────────────────────────────────────────────
    poll_sec_title:'📊 Bình chọn nghề yêu thích',
    poll_total_label:'Tổng',
    poll_total_unit:'lượt bình chọn',
    poll_tab1:'📚 Bài 1',
    poll_tab2:'💻 Phần mềm',
    poll_tab3:'🚀 Chuyển đổi số',
    poll_tab4:'🎨 Truyền thông',
    poll_q1:'Trong Bài 1, bạn thấy nghề nào hấp dẫn nhất?',
    poll_q2:'Trong ngành Công nghiệp phần mềm, bạn chọn nghề nào?',
    poll_q3:'Nghề nào trong Chuyển đổi số bạn thấy tương lai nhất?',
    poll_q4:'Lĩnh vực nào trong Truyền thông đa phương tiện bạn thích?',
    poll_opt_bai1_1:'Kĩ thuật viên CNTT',
    poll_opt_bai1_2:'Kĩ sư An toàn Thông tin',
    poll_opt_bai1_3:'Kĩ sư Quản trị Mạng',
    poll_opt_bai1_4:'Quản trị & Bảo trì Hệ thống',
    poll_opt_pm_1:'Kiểm thử viên',
    poll_opt_pm_2:'Người quản lí Kiểm thử',
    poll_opt_pm_3:'Nhà thiết kế UI/UX',
    poll_opt_cds_1:'Kĩ sư Điện toán Đám mây',
    poll_opt_cds_2:'Kĩ sư IoT',
    poll_opt_cds_3:'Kĩ sư Trí tuệ Nhân tạo (AI)',
    poll_opt_media_1:'Thiết kế Đồ hoạ',
    poll_opt_media_2:'Thiết kế TTĐPT',
    poll_opt_media_3:'Nhà phát triển Trang web',
    poll_opt_media_4:'Kĩ xảo Điện ảnh',
    // ── Comments ─────────────────────────────────────────────
    bl_title:'Chia sẻ suy nghĩ của bạn',
    bl_sub:'Nghề CNTT nào trong Chủ đề G bạn quan tâm nhất?',
    bl_placeholder_name:'Họ và tên...',
    bl_placeholder_content:'Nghề CNTT nào bạn muốn theo đuổi? Tại sao?...',
    bl_select_default:'-- Chọn nghề yêu thích --',
    bl_optgroup1:'Bài 1 – Dịch vụ',
    bl_optgroup2:'Bài 1 – Quản trị',
    bl_optgroup3:'Bài 2 – Công nghiệp phần mềm',
    bl_optgroup4:'Bài 2 – Chuyển đổi số',
    bl_optgroup5:'Bài 2 – Truyền thông đa phương tiện',
    bl_optgroup6:'Bài 2 – Ứng dụng CNTT ngành khác',
    bl_emotion_label:'Cảm xúc:',
    bl_submit_btn:'GỬI BÌNH LUẬN ✈',
    bl_filter_all:'TẤT CẢ',
    bl_filter_new:'MỚI NHẤT',
    bl_filter_popular:'NHIỀU ♥',
    bl_search_placeholder:'Tìm bình luận...',
    // ── Toast messages ────────────────────────────────────────
    toast_copy:'🔗 Đã sao chép link!',
    toast_comment_sent:'✓ Đã gửi bình luận thành công!',
    toast_comment_required:'⚠ Vui lòng nhập tên và nội dung!',
    toast_bookmark_save:'🔖 Đã lưu bài viết!',
    toast_bookmark_remove:'🔖 Đã bỏ lưu',
    toast_poll_voted:'✓ Đã ghi nhận bình chọn của bạn!',
    // ── Footer ────────────────────────────────────────────────
    footer_about_title:'Thông tin về nhóm',
    footer_author:'Tác giả:',
    footer_class:'Lớp:',
    footer_school:'Trường:',
    footer_subject:'Môn:',
    footer_subject_val:'Tin học – Bài 12, Chủ đề G',
    footer_updated:'Ngày cập nhật nội dung gần nhất:',
    footer_email:'Địa chỉ email:',
    footer_sources_title:'Nguồn thông tin tham khảo',
    footer_copy:'© 2026 Báo Tường Điện Tử – Hướng nghiệp với Tin học – Chủ đề G – Tin học 12',
    // ── Misc UI ───────────────────────────────────────────────
    back_to_top_title:'Lên đầu trang',
    search_placeholder:'Tìm kiếm...',
    live_search_title:'Tìm kiếm',
    bookmark_title:'Lưu',
};