/* =============================================
   LANG: 🇬🇧 English (EN)
   Chủ đề G – Hướng nghiệp với Tin học
============================================= */
window.LANGS = window.LANGS || {};
window.LANGS['en'] = {
// ── Header / Nav ──────────────────────────────────────────
    badge:'Topic G - Career Guidance with IT',
    h1line1:'Explore the World of<br>Information Technology',
    subtitle:'Introducing IT Service, Management & Application career groups',
    readtime:'Reading time:',
    nav1:'Introduction', nav2:'Articles', nav3:'Photo Gallery',
    nav4:'Music & Video', nav5:'Career Explorer', nav6:'Poll', nav7:'Comments',
    // ── Section titles ────────────────────────────────────────
    sec1:'Introduction', sec2:'Articles', sec3:'Photo Gallery',
    sec4:'Music & Video Clips', sec7:'Comments',
    copylink:'Copy link',
    themeLight:'Light', themeDark:'Dark',
    readingMin:'min',
    // ── Intro section ─────────────────────────────────────────
    intro_title:'Topic G – Career Guidance with IT',
    intro_p1:'Information Technology (IT) is a rapidly growing industry with very high demand for human resources in Vietnam. Vietnam is implementing the <strong style="color:#ff9999;">National Digital Transformation Program</strong> approved by the Prime Minister in June 2020, creating tens of thousands of job opportunities every year.',
    intro_p2:'<strong style="color:#ff9999;">Lesson 1</strong> introduces the <em>Service</em> career group (IT Technician, Information Security Engineer) and the <em>Management</em> career group (Network Engineer, System Administration & Maintenance).',
    intro_p3:'<strong style="color:#ff9999;">Lesson 2</strong> introduces careers in <em>Software Industry</em> (3 careers), <em>Digital Transformation</em> (3 careers), <em>Multimedia Communications</em> (4 careers) and <em>IT Applications in Other Fields</em> (3 careers).',
    stat1:'IT engineers recruited per year in Vietnam',
    stat2:'Career groups in Lesson 1 (Service & Management)',
    stat3:'Career groups in Lesson 2',
    stat4:'Total careers introduced in Topic G',
    // ── Flip card group headings ──────────────────────────────
    nhom_dv:'LESSON 1 – SERVICE CAREERS IN IT',
    nhom_qt:'LESSON 1 – MANAGEMENT CAREERS IN IT',
    nhom_pm:'LESSON 2 – GROUP 1: SOFTWARE INDUSTRY CAREERS',
    nhom_cds:'LESSON 2 – GROUP 2: DIGITAL TRANSFORMATION CAREERS',
    nhom_tt:'LESSON 2 – GROUP 3: MULTIMEDIA COMMUNICATIONS CAREERS',
    nhom_ud:'LESSON 2 – GROUP 4: IT APPLICATIONS IN OTHER FIELDS',
    // ── Photo captions ────────────────────────────────────────
    cap1:'IT Technician repairing and maintaining computer hardware',
    cap2:'Security Operations Center (SOC) monitoring systems 24/7',
    cap3:'Network engineer operating enterprise network systems',
    cap4:'AI engineer researching and developing artificial intelligence models',
    cap5:'GIS specialist building digital maps for urban planning',
    cap6:'UI/UX designer crafting interfaces and user experiences',
    // ── Video cards ───────────────────────────────────────────
    vid1_title:'IT Technician – A Day in the Life',
    vid1_desc:'A real look at the daily work of an IT technician in Vietnam',
    vid2_title:'Information Security Engineer – The Hottest Job in the Digital Age',
    vid2_desc:'Why is information security the most sought-after field right now?',
    vid3_title:'Digital Transformation – New Career Opportunities',
    vid3_desc:'AI Engineer, IoT Engineer, Cloud Engineer – careers of the digital future',
    vid4_title:'Career Guidance – Choosing the Right IT Field for You',
    vid4_desc:'Tips on choosing a career that fits your interests and strengths',
    // ── Flip card content ─────────────────────────────────────
    flip_hint:'🔄 Hover for details',
    // IT Technician
    ktvcntt_tooltip:'Provides hardware & software tech support at organisations',
    ktvcntt_title:'a) IT Technician',
    ktvcntt_desc:'An IT technician performs tasks requiring IT knowledge and skills (hardware and software) at organisations and enterprises.',
    ktvcntt_li1:'Troubleshoot and repair computers for clients',
    ktvcntt_li2:'Advise on hardware and software upgrades',
    ktvcntt_li3:'Install equipment and set up network connections',
    ktvcntt_li4:'Manage computers and peripheral devices',
    ktvcntt_back_h:'💡 Salary & Requirements',
    ktvcntt_back1:'Starting salary: 8–15 million VND/month',
    ktvcntt_back2:'Experienced: 15–30 million VND/month',
    ktvcntt_back3:'Need: Hardware knowledge, Windows/Linux',
    ktvcntt_back4:'Degree: College/Uni IT or CompTIA A+ certificate',
    ktvcntt_back5:'Personality: Patient, detail-oriented, problem-solver',
    // Information Security Engineer
    attt_tooltip:'Protects systems from cyberattacks & data breaches',
    attt_title:'b) Information Security Engineer',
    attt_desc:'Build and maintain data security solutions, protect information and recover systems when incidents occur.',
    attt_li1:'Establish and enforce information security policies',
    attt_li2:'Monitor and alert on suspicious activity',
    attt_li3:'Develop and execute incident response plans',
    attt_li4:'Advise development teams on security practices',
    attt_back_h:'💡 Salary & Requirements',
    attt_back1:'Starting salary: 15–25 million VND/month',
    attt_back2:'Senior: 40–80 million VND/month',
    attt_back3:'Certifications: CEH, CISSP, CompTIA Security+',
    attt_back4:'Skills: Penetration testing, encryption, firewalls',
    attt_back5:'Personality: Analytical thinker, meticulous',
    // Network Engineer
    qtm_tooltip:'Keeps network systems stable and secure at all times',
    qtm_title:'a) Network Engineer',
    qtm_desc:'Ensure computer network systems are always stable and operating securely, including managing, operating, configuring and protecting networks.',
    qtm_li1:'Manage network devices, configure and optimise performance',
    qtm_li2:'Protect networks from attacks and unauthorised access',
    qtm_li3:'Troubleshoot network issues',
    qtm_back_h:'💡 Salary & Requirements',
    qtm_back1:'Salary: 12–30 million VND/month',
    qtm_back2:'Certifications: CCNA, CCNP (Cisco)',
    qtm_back3:'Skills: TCP/IP, VPN, Routing & Switching',
    qtm_back4:'Personality: Thorough, quick incident response',
    // System Administration & Maintenance
    btht_tooltip:'Manages the entire IT infrastructure of an organisation',
    btht_title:'b) System Administration & Maintenance',
    btht_desc:'Manage both software and hardware related to the operation of computer network systems and data communications.',
    btht_li1:'Analyse organisational IT system requirements',
    btht_li2:'Install hardware and software for network systems',
    btht_li3:'Optimise and evaluate system performance',
    btht_back_h:'💡 Salary & Requirements',
    btht_back1:'Salary: 15–35 million VND/month',
    btht_back2:'Skills: Windows Server, Linux, VMware',
    btht_back3:'Must know: Active Directory, backup, monitoring',
    btht_back4:'Personality: Responsible, systems thinker',
    // Software Tester
    ktv_title:'a) Software Tester',
    ktv_desc:'Run software tests to verify it meets design and operational requirements, then find and report bugs to the development team.',
    ktv_note:'<strong style="color:#ff9999;"><img src="images/check (1).png" alt="" style="width:20px;height:20px;vertical-align:text-bottom;"> No advanced programming skills required!</strong>',
    ktv_back_h:'💡 Salary & Requirements',
    ktv_back1:'Salary: 8–20 million VND/month',
    ktv_back2:'Certification: ISTQB Foundation Level',
    ktv_back3:'Skills: Test cases, bug reports, Jira, Selenium',
    ktv_back4:'No strong coding needed — logical thinking is key',
    ktv_back5:'Personality: Detail-oriented, patient, questioning',
    // Test Manager
    qlkt_title:'b) Test Manager',
    qlkt_desc:'Establish testing processes, write test scripts, plan and assign work for testers to execute.',
    qlkt_back_h:'💡 Salary & Requirements',
    qlkt_back1:'Salary: 20–45 million VND/month',
    qlkt_back2:'Experience: 3–5 years as a software tester',
    qlkt_back3:'Skills: Project management, test planning',
    qlkt_back4:'Personality: Leadership, great communicator, decisive',
    // UI/UX Designer
    uiux_title:'c) UI Designer & UX Designer (UI/UX)',
    uiux_desc:'Ensure software products are user-friendly, attractive and easy to use. Apply psychology and ergonomics to tailor features for users.',
    uiux_note:'<strong style="color:#ff9999;">No programming skills needed — creative thinking is the key!</strong>',
    uiux_back_h:'💡 Salary & Tools',
    uiux_back1:'Salary: 12–35 million/month; Senior: 50 million+',
    uiux_back2:'Tools: Figma, Adobe XD, Sketch, Zeplin',
    uiux_back3:'A design portfolio is an essential requirement',
    uiux_back4:'Knowledge of colour psychology, UX research',
    uiux_back5:'Personality: Creative, empathetic towards users',
    // Cloud Engineer
    cloud_title:'a) Cloud Computing Engineer',
    cloud_desc:'Design, develop, maintain and troubleshoot cloud infrastructure. Use internet servers to store, process and analyse data.',
    cloud_back_h:'💡 Salary & Requirements',
    cloud_back1:'Salary: 20–50 million VND/month',
    cloud_back2:'Certifications: AWS Solutions Architect, GCP, Azure',
    cloud_back3:'Skills: Docker, Kubernetes, Terraform, CI/CD',
    cloud_back4:'Personality: Infrastructure mindset, loves automation',
    // IoT Engineer
    iot_title:'b) IoT Engineer',
    iot_desc:'Design, develop, deploy and maintain IoT systems — networks of devices that exchange information in real time.',
    iot_back_h:'💡 Salary & Requirements',
    iot_back1:'Salary: 15–40 million VND/month',
    iot_back2:'Skills: Embedded C, MQTT, Raspberry Pi, Arduino',
    iot_back3:'Combines: Electronics + Software + Networking',
    iot_back4:'Personality: Loves both hardware and software',
    // AI Engineer
    ai_title:'AI Engineer (Artificial Intelligence)',
    ai_desc:'Build AI models, manage AI development processes and ensure the latest AI research results are deployed into production. The hottest field right now.',
    ai_back_h:'💡 Salary & Requirements',
    ai_back1:'Salary: 25–80 million/month; Senior: 100 million+',
    ai_back2:'Skills: Python, TensorFlow, PyTorch, ML pipelines',
    ai_back3:'Maths: Linear algebra, probability and statistics',
    ai_back4:'Personality: Research-driven, high analytical thinking',
    // Graphic Designer
    thietkedohoa_title:'a) Graphic Designer',
    thietkedohoa_desc:'Select typefaces, colours, shapes, images and the overall layout of graphic products using Photoshop, Illustrator, Sketch… No programming required.',
    thietkedohoa_back_h:'💡 Salary & Requirements',
    thietkedohoa_back1:'Salary: 8–22 million/month; Freelance: unlimited',
    thietkedohoa_back2:'Tools: Photoshop, Illustrator, CorelDRAW',
    thietkedohoa_back3:'Portfolio is the deciding factor when applying',
    thietkedohoa_back4:'Personality: Creative, strong aesthetic sense',
    // Multimedia Designer
    ttdpt_title:'b) Multimedia Communications Designer',
    ttdpt_desc:'Design, process and edit audio and visuals for digital products, combining multimedia techniques with mass communications.',
    ttdpt_back_h:'💡 Salary & Requirements',
    ttdpt_back1:'Salary: 10–25 million VND/month',
    ttdpt_back2:'Tools: Premiere Pro, After Effects, Audition',
    ttdpt_back3:'Need: Visual/audio storytelling skills',
    ttdpt_back4:'Personality: Creative, sensitive to art',
    // Web Developer
    webdev_title:'c) Web Developer',
    webdev_desc:'Design interfaces, code websites, test and fix performance or user-experience issues.',
    webdev_back_h:'💡 Salary & Requirements',
    webdev_back1:'Salary: 12–40 million/month; Full-stack: 50 million+',
    webdev_back2:'Frontend: HTML, CSS, JS, React/Vue',
    webdev_back3:'Backend: Node.js, PHP, Python, Java',
    webdev_back4:'Personality: Logical + creative, loves building things',
    // VFX Artist
    vfx_title:'d) Visual Effects (VFX) Artist',
    vfx_desc:'Ensure audio and visual effects deliver the most authentic emotions and accurately convey the producer\'s message.',
    vfx_back_h:'💡 Salary & Requirements',
    vfx_back1:'Salary: 15–50 million/month (project-based)',
    vfx_back2:'Tools: Nuke, Houdini, Maya, Blender',
    vfx_back3:'Booming industry — Vietnamese films and advertising',
    vfx_back4:'Personality: Creative, attention to every detail',
    // Data Analyst / Data Scientist
    data_title:'a) Data Analyst & Data Scientist',
    data_desc:'Analyse datasets to identify trends, detect anomalies and uncover hidden insights that inform leadership decisions.',
    data_back_h:'💡 Salary & Requirements',
    data_back1:'Salary: 18–50 million VND/month',
    data_back2:'Skills: Python/R, SQL, Tableau, Power BI',
    data_back3:'Need: Statistical maths, data analysis mindset',
    data_back4:'Personality: Curious, loves finding patterns in data',
    // GIS Engineer
    gis_title:'b) GIS Engineer (Geographic Information Systems)',
    gis_desc:'Build digital maps, maintain geographic databases and analyse data using GIS tools for a wide range of applications.',
    gis_back_h:'💡 Salary & Requirements',
    gis_back1:'Salary: 12–28 million VND/month',
    gis_back2:'Tools: ArcGIS, QGIS, Python, PostGIS',
    gis_back3:'Applications: Urban planning, defence, environment',
    gis_back4:'Personality: Detail-oriented, loves maps and spatial data',
    // Fintech Engineer
    fintech_title:'c) Financial Technology Engineer (Fintech)',
    fintech_desc:'Apply advanced technology to improve financial services using cloud computing, data analytics and AI in finance and banking.',
    fintech_back_h:'💡 Salary & Requirements',
    fintech_back1:'Salary: 20–60 million VND/month',
    fintech_back2:'Skills: Blockchain, financial APIs, payment security',
    fintech_back3:'Combines: IT + Finance & Banking',
    fintech_back4:'Personality: Careful, understands financial regulations',
    // ── Quiz ─────────────────────────────────────────────────
    quiz_sec_title:'🧠 Discover the right career for you',
    quiz_intro_h:'Which IT Career Is Right for You?',
    quiz_intro_p:'Answer 10 short questions about your personality and interests. The results will show you <strong style="color:var(--purple-light)">the 2 most suitable careers</strong> with match percentages — because sometimes the path you choose isn\'t #1!',
    quiz_start_btn:'START EXPLORING →',
    quiz_q_label:'QUESTION',
    quiz_rank1:'★ BEST MATCH',
    quiz_rank2:'✦ SUGGESTION 2',
    quiz_match_label:'Match level',
    quiz_learn_btn:'📖 Learn more →',
    quiz_res_title:'Your Results',
    quiz_res_sub:'Based on your answers, here are the 2 careers that suit you best',
    quiz_note_html:'<strong>💡 Important note:</strong> These results are for reference only based on personality trends. If you prefer the 2nd career — <strong>go for it!</strong> Passion and effort always matter more than any test.',
    quiz_restart_btn:'🔄 Try again',
    // ── Poll ─────────────────────────────────────────────────
    poll_sec_title:'📊 Vote for your favourite career',
    poll_total_label:'Total',
    poll_total_unit:'votes',
    poll_tab1:'📚 Lesson 1',
    poll_tab2:'💻 Software',
    poll_tab3:'🚀 Digital',
    poll_tab4:'🎨 Media',
    poll_q1:'In Lesson 1, which career do you find most attractive?',
    poll_q2:'In the Software Industry, which career would you choose?',
    poll_q3:'Which Digital Transformation career do you see the most future in?',
    poll_q4:'Which field of Multimedia Communications do you prefer?',
    poll_opt_bai1_1:'IT Technician',
    poll_opt_bai1_2:'Information Security Engineer',
    poll_opt_bai1_3:'Network Engineer',
    poll_opt_bai1_4:'System Administration & Maintenance',
    poll_opt_pm_1:'Software Tester',
    poll_opt_pm_2:'Test Manager',
    poll_opt_pm_3:'UI/UX Designer',
    poll_opt_cds_1:'Cloud Computing Engineer',
    poll_opt_cds_2:'IoT Engineer',
    poll_opt_cds_3:'AI Engineer',
    poll_opt_media_1:'Graphic Designer',
    poll_opt_media_2:'Multimedia Designer',
    poll_opt_media_3:'Web Developer',
    poll_opt_media_4:'VFX Artist',
    // ── Comments ─────────────────────────────────────────────
    bl_title:'Share Your Thoughts',
    bl_sub:'Which IT career in Topic G interests you most?',
    bl_form_title_label:'Share your thoughts',
    bl_placeholder_name:'Full name...',
    bl_placeholder_content:'Which IT career do you want to pursue? Why?...',
    bl_select_default:'-- Choose your favourite career --',
    bl_optgroup1:'Lesson 1 – Service',
    bl_optgroup2:'Lesson 1 – Management',
    bl_optgroup3:'Lesson 2 – Software Industry',
    bl_optgroup4:'Lesson 2 – Digital Transformation',
    bl_optgroup5:'Lesson 2 – Multimedia',
    bl_optgroup6:'Lesson 2 – IT Applications',
    bl_emotion_label:'Mood:',
    bl_submit_btn:'SEND COMMENT ✈',
    bl_filter_all:'ALL',
    bl_filter_new:'NEWEST',
    bl_filter_popular:'MOST LIKED ♥',
    bl_search_placeholder:'Search comments...',
    // ── Toast messages ────────────────────────────────────────
    toast_copy:'🔗 Link copied!',
    toast_comment_sent:'✓ Comment sent successfully!',
    toast_comment_required:'⚠ Please enter your name and comment!',
    toast_bookmark_save:'🔖 Article saved!',
    toast_bookmark_remove:'🔖 Article removed from saved',
    toast_poll_voted:'✓ Your vote has been recorded!',
    // ── Footer ────────────────────────────────────────────────
    footer_about_title:'About the Group',
    footer_author:'Author:',
    footer_class:'Class:',
    footer_school:'School:',
    footer_subject:'Subject:',
    footer_subject_val:'Informatics – Lesson 12, Topic G',
    footer_updated:'Last updated:',
    footer_email:'Email:',
    footer_sources_title:'Reference Sources',
    footer_copy:'© 2026 Digital Wall Newspaper – Career Guidance with IT – Topic G – Informatics 12',
    // ── Misc UI ───────────────────────────────────────────────
    back_to_top_title:'Back to top',
    search_placeholder:'Search...',
    live_search_title:'Search',
    bookmark_title:'Save',
};